### ISSUE TITLE
Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by 1261017506** [KinglittleQ/PSMNet#1]
self.disp_score = torch.range(0, max_disp - 1)  # [D]
Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main(args)
  File "train.py", line 75, in main
    model.load_state_dict(state['state_dict'])
  File "/home/cb/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PSMNet:
        Missing key(s) in state_dict: "cost_net.cnn.conv0.0.net.0.weight", "cost_net.cnn.conv0.0.net.1.weight", "cost_net.cnn.conv0.0.net.1.bias", "cost_net.cnn.conv0.0.net.1.running_mean", "cost_net.cnn.conv0.0.net.1.running_var", "cost_net.cnn.conv0.1.net.0.weight", "cost_net.cnn.conv0.1.net.1.weight",

**Comment by KinglittleQ** [comment]
Did you use one GPU?

**Comment by HuangGuoHui110** [comment]
> Did you use one GPU and comment out the `model = nn.DataPararell(model, device_ids)`?
Hi, I have the same problem.I run train.py by one GPU, and i get errors when i try to test the model. How should I save the model in training and call my own trained model in the test to avoid such errors?Thanks!
This is my errors:
KeyError: 'unexpected key "state_dict" in state_dict'

**Comment by KinglittleQ** [comment]
Try to comment out [this](https://github.com/KinglittleQ/PSMNet/blob/b02fadb81fd1ba6a83c84ded3fc0139b709c0388/inference.py#L47) segment code.

**Comment by HuangGuoHui110** [comment]
Thanks a lot! It's helpful  for me.
