### ISSUE TITLE
Can you provide the evaluation result for KITTI dataset?

### ISSUE THREAD

**Issue by chenyilun95** [KinglittleQ/PSMNet#2]
Thanks very much for providing the pytorch-reimplementation of PSMnet.

Do you reproduce the result of original paper or match the result of the original code? Can you provide the evaluation result for KITTI dataset ?

**Comment by KinglittleQ** [comment]
I didn't train the model on Scene Flow dataset so the performance on KITTI is slightly lower than the result of the original paper. The 3px error of my training model is 3.466 which has been mentioned on the README.

**Comment by chenyilun95** [comment]
Thanks for your response !
