### ISSUE TITLE
RuntimeError: Cuda out of memory.

### ISSUE THREAD

**Issue by Shelomith** [KinglittleQ/PSMNet#3]
hi there:
I changed the batchsize to 1, and run the code. 
There is an
RuntimeError: CUDA out of memory. Tried to allocate 352.00 MiB (GPU 0; 5.93 GiB total capacity; 3.99 GiB already allocated; 32.56 MiB free; 782.19 MiB cached).

What's the GPU you used? and how many time you used to train the model?

**Comment by KinglittleQ** [comment]
Rewrite [here ](https://github.com/KinglittleQ/PSMNet/blob/b02fadb81fd1ba6a83c84ded3fc0139b709c0388/train.py#L45) to your available GPU numbers.

I took several days to train my model.
