### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jackyangs** [KinglittleQ/PSMNet#8]
Hello
When I run to the verification step, the 3px-error rate always shows 0. Can you tell me where there is a problem？
I found that **target_disp** read the value of 0, but, I don't know where it is.
Can you help me with it？

**Comment by KinglittleQ** [comment]
Did you mean target_disp is always 0? You may need to check the path of the disparity map here https://github.com/KinglittleQ/PSMNet/blob/897c45facaa176e70ab43cb6aefd5427da1f1b2a/dataloader/KITTI2015_loader.py#L67
Simply printing the path and the read disparity map may help you.

**Comment by jackyangs** [comment]
Thank you for your reply. I'll try again
